In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression 

from sklearn.metrics import accuracy_score

In [4]:
import seaborn as sns
df=sns.load_dataset('titanic')

In [5]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [7]:
df.drop(columns=['sex','sibsp','parch','embarked','class','who','adult_male','deck','embark_town','alive','alone'],inplace=True)

In [8]:
df.head()

   survived  pclass   age     fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [9]:
df.isnull().mean()*100

survived     0.00000
pclass       0.00000
age         19.86532
fare         0.00000
dtype: float64

In [10]:
X=df.drop(columns=['survived'])
y=df['survived']

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
X_train.head()

     pclass   age     fare
331       1  45.5  28.5000
733       2  23.0  13.0000
382       3  32.0   7.9250
704       3  26.0   7.8542
813       3   6.0  31.2750

In [22]:
knn=KNNImputer(n_neighbors=5,weights='distance')
X_train_trf=knn.fit_transform(X_train)
X_test_trf=knn.transform(X_test)

In [23]:
pd.DataFrame(X_train_trf,columns=X_train.columns)

     pclass        age      fare
0       1.0  45.500000   28.5000
1       2.0  23.000000   13.0000
2       3.0  32.000000    7.9250
3       3.0  26.000000    7.8542
4       3.0   6.000000   31.2750
..      ...        ...       ...
707     3.0  21.000000    7.6500
708     1.0  40.111111   31.0000
709     3.0  41.000000   14.1083
710     1.0  14.000000  120.0000
711     1.0  21.000000   77.2875

[712 rows x 3 columns]

In [24]:
lr=LogisticRegression()
lr.fit(X_train_trf,y_train)
y_pred=lr.predict(X_test_trf)
accuracy_score(y_test,y_pred)

0.7374301675977654

In [25]:
si=SimpleImputer()
X_train_trf2=si.fit_transform(X_train)
X_test_trf2=si.transform(X_test)

In [26]:
lr=LogisticRegression()
lr.fit(X_train_trf2,y_train)
y_pred=lr.predict(X_test_trf2)
accuracy_score(y_test,y_pred)

0.7374301675977654